---
- name: install redis ppa
  apt_repository: repo={{redis_apt_repository}}
  when: redis_apt_repository

- name: install redis-server
  apt: name=redis-server

- name: configure redis-server
  template:
    src=redis.conf.j2
    dest=/etc/redis/redis.conf
  notify:
    - restart redis
