---
- hosts: all
  roles:
    - common
    - rsyslog
  tags: ['provision']

- hosts: server_postgres
  roles:
    - postgres-server-archive
    - postgres-server
    - role: firewall-group
      port: "{{ postgres_server.port }}"
      group: server_application
  tags: ['provision']

- hosts: server_redis
  roles:
    - redis
    - role: firewall-group
      port: "{{ redis_server.port }}"
      group: server_application
  tags: ['provision']

- hosts: server_application
  roles:
    - app-base
    - supervisor
    - nginx-base
    - role: firewall
      rules:
        - port: "80/tcp"
        - port: "443/tcp"
  tags: ['provision','app']

- hosts: server_application_nodejs
  roles:
    - app-nodejs-base
  tags: ['provision','app','nodejs']

- hosts: server_postgres
  roles:
    - postgres-server-host
  tags: ['provision','app']

- hosts: server_application_rails
  roles:
    - app-rails-base
  tags: ['provision','app','rails']

- include: play-nodeapp.yml
- include: play-railsapp.yml
