---
- hosts: all
  roles:
    - common
    - rsyslog
  tags: ['provision']

- hosts: server_postgres
  roles:
    - postgres-server
  tags: ['provision']

- hosts: server_redis
  roles:
    - redis
  tags: ['provision']

- hosts: server_application
  roles:
    - app-base
    - supervisor
    - nginx-base
  tags: ['provision','app']

- hosts: server_application_nodejs
  roles:
    - app-nodejs-base
  tags: ['provision','app','nodejs']

- hosts: server_postgres
  roles:
    - postgres-server-host
  tags: ['provision','app']

- hosts: server_application_rails
  roles:
    - app-rails-base
  tags: ['provision','app','rails']

# nodeapp playbook
- hosts: nodeapp_app_servers
  roles:
    - app-checkout-pending
    - role: app-configure
      files:
        - name: http.json
          format: json
          content:
            port: "{{ application.web.port }}"
        - name: redis.json
          format: json
          content:
            host: "{{ application.redis.host }}"
            port: "{{ application.redis.port }}"
    - app-nodejs-npm
    - app-nginx
    - app-checkout-finalize
    - app-nodejs-finalize
  tags: ['deploy','app','app-nodeapp']
  vars_files:
    - "vars/nodeapp.yml"

# railsapp playbook
- hosts: railsapp_app_servers
  roles:
    - app-checkout-pending
    - role: app-configure
      files:
        - name: database.yml
          format: yml
          content:
            production:
              host:     "{{ application.database.host     }}"
              port:     "{{ application.database.port     }}"
              username: "{{ application.database.username }}"
              password: "{{ application.database.password }}"
              database: "{{ application.database.database }}"
              adapter:  "{{ application.database.adapter  }}"
              encoding: "{{ application.database.encoding }}"
              pool:     "{{ application.database.pool     }}"
    - app-rails-bundle
    - role: app-rails-rake
      commands:
        - "assets:precompile"
        - "db:migrate"
    - app-rails-unicorn
    - app-nginx
    - app-checkout-finalize
    - app-rails-finalize
  vars_files:
    - "vars/railsapp.yml"
