---
- hosts: default
  vars:
    postgresql_databases:
      - name: testapp_1
        password: testapp_1_password
      - name: testapp_2
        password: testapp_2_password

  roles:
    - common
    - postgres-server
    - rsyslog
    - redis

  tasks:
    - name: install common packages
      action: apt name={{item}} state=installed
      with_items:
        - supervisor
        - build-essential
        - nginx-full
        - ruby1.9.3
        - libpq-dev

    - name: install common gems
      action: gem name={{item}}
      with_items:
        - bundler
