- name: create base directories
  file: path={{app_dir}} state=directory

- name: create application directories
  file:
    path={{app_dir}}/{{application.name}}/{{item}} state=directory
  with_items:
    - ['bin', 'shared', 'releases']

- name: create deploy-owned directories
  file:
    path={{app_dir}}/{{application.name}}/shared/{{item}}
    owner={{deploy.username}}
    state=directory
  with_items:
    - [ 'log', 'pids' ]

- name: create git ssh script
  copy: src=git-ssh.sh
       dest={{app_dir}}/{{application.name}}/bin/git-ssh.sh
       mode=0755

- name: copy ssh private key
  copy: src={{private_keys_dir}}/{{application.deploy_key}}
       dest={{app_dir}}/{{application.name}}/bin/deploy.key
       mode=0600
  when: application.deploy_key is defined

- name: get head revision
  raw: GIT_SSH={{app_dir}}/{{application.name}}/bin/git-ssh.sh git ls-remote "{{application.repo.source}}" "{{application.repo.branch}}" 2>/dev/null | grep -v "Permanently added" | cut -f1
  register: application_revision

- name: checkout head revision
  git:
    depth=1
    repo={{application.repo.source}}
    dest={{app_dir}}/{{application.name}}/releases/{{application_revision.stdout}}
    version={{application_revision.stdout}}
    key_file={{app_dir}}/{{application.name}}/bin/deploy.key
    accept_hostkey=True

- name: create pending release link
  file: state=link
        force=yes
        src={{app_dir}}/{{application.name}}/releases/{{application_revision.stdout}}
        dest={{app_dir}}/{{application.name}}/releases/pending

- name: remove deploy-owned directories for symlinking
  raw: "[ -d '{{app_dir}}/{{application.name}}/releases/pending/{{ item }}' ] && rm -rf {{app_dir}}/{{application.name}}/releases/pending/{{ item }}; true"
  with_items: [ 'log' ]

- name: symlink deploy-owned directories
  file: state=link
        force=yes
        src={{ app_dir }}/{{ application.name }}/shared/{{ item }}
        dest={{ app_dir }}/{{application.name}}/releases/pending/{{ item }}
  with_items: [ 'log' ]

- name: create VERSION file
  copy: content={{application_revision.stdout}}
        dest={{app_dir}}/{{application.name}}/releases/pending/VERSION

