---
- name: install nodejs ppa
  apt_repository: repo=ppa:chris-lea/node.js

- name: install nodejs
  apt: name=nodejs

- name: npm install
  npm: path={{app_dir}}/{{item.name}}/releases/pending
       state=present
  with_items: applications
  when: item.type == "nodejs"

- name: install launcher
  template:
    src=supervisor.conf.j2
    dest={{supervisor.conf_dir}}/{{item.name}}.conf
  with_items: applications
  when: item.type == "nodejs"

- name: install current symlink
  file:
    state=link
    force=yes
    src={{app_dir}}/{{item.item.name}}/releases/{{item.stdout}}
    dest={{app_dir}}/{{item.item.name}}/current
  with_items: application_revisions.results
  when: item.item.type == "nodejs"

- name: restart supervisor
  supervisorctl: name={{item.name}} state=present
  with_items: applications
  when: item.type == "nodejs"

- name: restart supervisor
  supervisorctl: name={{item.name}} state=started
  with_items: applications
  when: item.type == "nodejs"
