---
- name: create the database user
  postgresql_user:
    name={{ item.key }}
    role_attr_flags=NOSUPERUSER,NOCREATEDB,NOCREATEROLE,NOINHERIT,LOGIN
    password={{ item.value.password }}
  sudo: yes
  sudo_user: "{{ postgres_server_user }}"
  with_dict: databases

- name: create database
  postgresql_db:
    name={{ item.key }}
    owner={{ item.key }}
  sudo: yes
  sudo_user: "{{ postgres_server_user }}"
  with_dict: databases

- name: revoke access to database from public
  postgresql_privs:
    db={{ item.key }}
    state=absent
    priv=ALL
    type=database
    obj={{ item.key }}
    role=public
  sudo: yes
  sudo_user: "{{ postgres_server_user }}"
  with_dict: databases

- name: grant access to database to user
  postgresql_privs:
    db={{ item.key }}
    priv=ALL
    type=schema
    obj=public
    role={{ item.key }}
    grant_option=yes
  sudo: yes
  sudo_user: "{{ postgres_server_user }}"
  with_dict: databases
