---
- name: create configuration directory
  file:
    path={{postgres_server_confdir}}/conf.d
    owner={{postgres_server_user}}
    group={{postgres_server_user}}
    state=directory

- name: install configuration files
  action:
    template
    src=postgresql.conf.{{item}}.j2
    dest={{postgres_server_confdir}}/conf.d/{{item}}.conf
    owner={{postgres_server_user}}
    group={{postgres_server_user}}
  with_items:
    - connections
    - resource-usage
    - wal
    - replication
    - tuning
    - logging
    - statistics
    - autovacuum
    - client
    - lock
    - compat
    - error

  notify:
    - restart postgresql

- name: install main configuration
  template:
    src=postgresql.conf.j2
    dest={{postgres_server_confdir}}/postgresql.conf
    owner={{postgres_server_user}}
    group={{postgres_server_user}}
  notify:
    - restart postgresql

- name: install pg_hba.conf
  template:
    src=pg_hba.conf.j2
    dest={{postgres_server_confdir}}/pg_hba.conf
    owner={{postgres_server_user}}
    group={{postgres_server_user}}
  notify:
    - restart postgresql
