---
- name: "revoke access to database postgres from public"
  postgresql_privs:
    db=postgres
    state=absent
    priv=ALL
    type=database
    obj=postgres
    role=public
  sudo_user: "{{ postgres_server_user }}"

- name: "revoke access to database template1 from public"
  postgresql_privs:
    db=template1
    state=absent
    priv=ALL
    type=database
    obj=template1
    role=public
  sudo_user: "{{ postgres_server_user }}"

- name: "revoke access to schema public from public"
  postgresql_privs:
    db=template1
    state=absent
    priv=ALL
    type=schema
    obj=public
    role=public
  sudo_user: "{{ postgres_server_user }}"

- name: "grant access to schema public to postgres"
  postgresql_privs:
    db=template1
    priv=ALL
    type=schema
    obj=public
    role="{{postgres_server_user}}"
  sudo_user: "{{ postgres_server_user }}"
