---
- name: "create the database user"
  postgresql_user:
    name={{item.name}}
    role_attr_flags=NOSUPERUSER,NOCREATEDB,NOCREATEROLE,NOINHERIT,LOGIN
    password={{item.password}}
  sudo_user: "{{ postgres_server_user }}"
  with_items: postgresql_databases

- name: "create databases"
  postgresql_db:
    name={{item.name}}
    owner={{item.name}}
  sudo: yes
  sudo_user: "{{ postgres_server_user }}"
  with_items: postgresql_databases

- name: "revoke access to database from public"
  postgresql_privs:
    db={{item.name}}
    state=absent
    priv=ALL
    type=database
    obj={{item.name}}
    role=public
  sudo: yes
  sudo_user: "{{ postgres_server_user }}"
  with_items: postgresql_databases

- name: "grant access to database to user"
  postgresql_privs:
    db={{item.name}}
    priv=ALL
    type=schema
    obj=public
    role={{item.name}}
    grant_option=yes
  sudo: yes
  sudo_user: "{{ postgres_server_user }}"
  with_items: postgresql_databases
