---
- name: install pycurl
  apt: name=python-pycurl

- name: install postgres apt key
  apt_key:
    url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
    key=0xACCC4CF8
    state=present

- name: install postgres apt repository
  apt_repository:
    repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_lsb.codename}}-pgdg main"

- name: install postgresql
  apt: name=postgresql-9.3

- name: install psycopg2
  apt: name=python-psycopg2
