---
- name: update and upgrade packages
  apt: update_cache=yes upgrade=safe cache_valid_time=604800

- name: install common packages
  action: apt name={{item}} state=installed
  with_items:
    - vim-nox
    - screen

- name: allow ssh
  command: ufw allow ssh/tcp

- name: enable ufw
  shell: echo 'y' | ufw enable
