---
- name: install nginx
  apt: name=nginx-extras

- name: disable default server
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: start nginx server
  service: name=nginx state=running
