---
- name: install git
  apt: name=git

- name: create deploy user
  user: name={{ deploy.username }} state=present shell=/bin/bash

- name: install deploy ssh keys
  authorized_key: user={{ deploy.username }} key="{{lookup('file',item)}}"
  with_fileglob:
    - "{{ deploy.public_keys }}"
